### ISSUE TITLE
Define interface files between metadata.xlsx and pxmake()

### ISSUE THREAD

**Issue by johan-ejstrud** [StatisticsGreenland/pxmake#75]
# To-do

## pxmake
- [ ] Create `excel_metadata_to_rds()` 
- [ ] Create `excel_source_data_to_rds()`
- [ ] Change `pxmake()` to use `excel_*_to_rds()` behind the scenes

## metamake
- [ ] Create `rds_to_excel()` that converts two rds files to excel.
- [ ] Let `metamake()` create `.rds` datasets instead of excel file.

## Other
- [ ] Change long_name to variablecode in `Variables` sheet (issue #139)
- [ ] Simplify calculation of precision (issue #66)
- [ ] Add helper function to convert a variable to a list of values (rowwise, mutate(list()), ungroup)
- [ ] Rename "source data" to "data table" (issue #141)
- [ ] Add tryCatch in get_data_table_df() to handle all cases.

# Questions
- Should interface files be in `.rds` format?
  - Start with `.rds`, should be easy to change later.
- Should interface be exposed to user or hidden? 
  - Start hidden, maybe expose later.   

# metadata format
- `keyword` name of keyword from px definition
- `sub-key/variable` usually NA, but used by a few keywords, e.g.`VALUES`, `DOMAIN`, to denote which variables it is connected to.
- `cell` Used by PRECISION to define the precision for specific values
- `language` NA or one of a number of languages
- `value` list of values 

# Description
pxmake is getting a bit bloated. Defining interface files `metadata.rds` and `source_data.rds` would have a couple of advantages:

- It's easier to clearly define what should be in `*.rds` files than in Excel files.
- All sanity checks can be done on the interface files.
- Avoid several reopens of excel files.
- Functions would have clearer responsabilities.
- It's possible to use `pxmake()` even if one doesn't use `metadata.xlsx`.

All these changes would be internal and wouldn't have big consequences for the user.

## Before
```mermaid
graph LR


    M --> P
    S --> P
    P --> O
    S -.-> P
    O --> MM
    MM --> M

    M["metadata.xlsx"]
    P["pxmake()"]
    S["source_data.rds"]
    O["output.px"]
    MM["metamake()"]

    style P fill:#bbf
    ;
```

## After (with `metamake()`)
```mermaid
graph LR

    M2 --> P
    S --> P
    P --> O
%%    O --> I
%%    I --> M2
%%    I --> S
%%    M2 --> I2
%%    S  --> I2
%%    I2 --> M 
    M --> C
    M -.-> C2
    C2 -.-> S
    C --> M2


    M["metadata.xlsx"]
    M2["metadata.rds"]
    C["excel_metadata_to_rds()"]
    C2["excel_source_data_to_rds()"]
    P["pxmake()"]
    S["source_data.rds"]
    O["output.px"]
  %%  I["metamake()"]
   %% I2["rds_to_excel()"]

    style P fill:#bbf
    style C fill:#bbf
    style C2 fill:#bbf
  %%  style I fill:#bbf
    ;
```

```mermaid
graph LR


    O --> I
    I --> M2
    I --> S
    
    %%M2 --> P
    %%S --> P
    %%P --> O
    M2 --> I2
    S  --> I2
    I2 --> M 
    %%M --> C
    %%M -.-> C2
    %%C2 -.-> S
    %%C --> M2


    M["metadata.xlsx"]
    M2["metadata.rds"]
    %%C["excel_metadata_to_rds()"]
    %%C2["excel_source_data_to_rds()"]
    %%P["pxmake()"]
    S["source_data.rds"]
    O["output.px"]
    I["metamake()"]
    I2["rds_to_excel()"]

    %%style P fill:#bbf
    %%style C fill:#bbf
    %%style C2 fill:#bbf
    style I fill:#bbf
    style I2 fill:#bbf
    ;
```

```mermaid
graph LR


    O --> I
    I --> M2
    I --> S
    
    %%M2 --> P
    %%S --> P
    %%P --> O
    M2 --> P
    S  --> P
    P --> O
    %%M --> C
    %%M -.-> C2
    %%C2 -.-> S
    %%C --> M2


    %%M["metadata.xlsx"]
    M2["metadata.rds"]
    %%C["excel_metadata_to_rds()"]
    %%C2["excel_source_data_to_rds()"]
    P["pxmake()"]
    S["source_data.rds"]
    O["output.px"]
    I["metamake()"]
    %%I2["rds_to_excel()"]

    style P fill:#bbf
    %%style C fill:#bbf
    %%style C2 fill:#bbf
    style I fill:#bbf
    %%style I2 fill:#bbf
    ;
```

**Comment by johan-ejstrud** [comment]
Det ville smart at gøre det her før implmenteringen af sanity checks og #71.
